[versions]
agp = "8.5.2"
kotlin = "2.0.0"
compose-bom = "2024.10.01"
activity-compose = "1.9.3"
lifecycle = "2.8.6"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-material3 = { module = "androidx.compose.material3:material3" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
material-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-ui-text = { module = "androidx.compose.ui:ui-text" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
